name: deepAL
channels:
  - pytorch
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/msys2
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/pro
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/r
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=4.5=1_gnu
  - arrow-cpp=4.0.1=py37hced866c_3
  - attrs=21.4.0=pyhd3eb1b0_0
  - aws-c-common=0.4.57=he6710b0_1
  - aws-c-event-stream=0.1.6=h2531618_5
  - aws-checksums=0.1.9=he6710b0_0
  - aws-sdk-cpp=1.8.185=hce553d0_0
  - blas=1.0=mkl
  - boost-cpp=1.73.0=h27cfd23_11
  - bottleneck=1.3.4=py37hce1f21e_0
  - brotli=1.0.9=he6710b0_2
  - brotlipy=0.7.0=py37h27cfd23_1003
  - bzip2=1.0.8=h7b6447c_0
  - c-ares=1.18.1=h7f8727e_0
  - ca-certificates=2022.4.26=h06a4308_0
  - catalogue=1.0.0=py37_1
  - certifi=2022.5.18.1=py37h06a4308_0
  - cffi=1.15.0=py37hd667e15_1
  - charset-normalizer=2.0.4=pyhd3eb1b0_0
  - configparser=5.0.2=pyhd3eb1b0_0
  - cryptography=36.0.0=py37h9ce1e76_0
  - cudatoolkit=10.2.89=hfd86e86_1
  - cycler=0.11.0=pyhd3eb1b0_0
  - cymem=2.0.6=py37h295c915_0
  - cython-blis=0.7.7=py37hce1f21e_0
  - dbus=1.13.18=hb2f20db_0
  - double-conversion=3.1.5=he6710b0_1
  - expat=2.4.4=h295c915_0
  - faiss-gpu=1.7.2=py3.7_h98e120b_0_cuda10.2
  - ffmpeg=4.3=hf484d3e_0
  - fontconfig=2.13.1=h6c09931_0
  - fonttools=4.25.0=pyhd3eb1b0_0
  - freetype=2.11.0=h70c0345_0
  - future=0.18.2=py37_1
  - gflags=2.2.2=he6710b0_0
  - giflib=5.2.1=h7b6447c_0
  - glib=2.69.1=h4ff587b_1
  - glog=0.3.5=0
  - gmp=6.2.1=h2531618_2
  - gnutls=3.6.15=he1e5248_0
  - grpc-cpp=1.26.0=hf8bcb03_0
  - gst-plugins-base=1.14.0=h8213a91_2
  - gstreamer=1.14.0=h28cd5cc_2
  - icu=58.2=he6710b0_3
  - idna=3.3=pyhd3eb1b0_0
  - importlib-metadata=4.11.3=py37h06a4308_0
  - importlib_metadata=4.11.3=hd3eb1b0_0
  - intel-openmp=2021.4.0=h06a4308_3561
  - joblib=1.1.0=pyhd3eb1b0_0
  - jpeg=9d=h7f8727e_0
  - jsonschema=3.0.2=py37_0
  - kiwisolver=1.3.2=py37h295c915_0
  - krb5=1.19.2=hac12032_0
  - lame=3.100=h7b6447c_0
  - lcms2=2.12=h3be6417_0
  - ld_impl_linux-64=2.35.1=h7274673_9
  - liac-arff=2.5.0=pyhd3eb1b0_1
  - libboost=1.73.0=h3ff78a5_11
  - libcurl=7.80.0=h0b77cf5_0
  - libedit=3.1.20210910=h7f8727e_0
  - libev=4.33=h7f8727e_1
  - libevent=2.0.22=0
  - libfaiss=1.7.2=hdbd6f0c_0_cuda10.2
  - libffi=3.3=he6710b0_2
  - libgcc-ng=9.3.0=h5101ec6_17
  - libgfortran-ng=7.5.0=ha8ba4b0_17
  - libgfortran4=7.5.0=ha8ba4b0_17
  - libgomp=9.3.0=h5101ec6_17
  - libiconv=1.15=h63c8f33_5
  - libidn2=2.3.2=h7f8727e_0
  - libnghttp2=1.46.0=hce63b2e_0
  - libpng=1.6.37=hbc83047_0
  - libprotobuf=3.11.2=hd408876_0
  - libssh2=1.9.0=h1ba5d50_1
  - libstdcxx-ng=9.3.0=hd4cf53a_17
  - libtasn1=4.16.0=h27cfd23_0
  - libthrift=0.13.0=hfb8234f_6
  - libtiff=4.2.0=h85742a9_0
  - libunistring=0.9.10=h27cfd23_0
  - libuuid=1.0.3=0
  - libuv=1.40.0=h7b6447c_0
  - libwebp=1.2.2=h55f646e_0
  - libwebp-base=1.2.2=h7f8727e_0
  - libxcb=1.14=h7b6447c_0
  - libxml2=2.9.12=h03d6c58_0
  - lz4-c=1.9.3=h295c915_1
  - matplotlib=3.5.1=py37h06a4308_1
  - matplotlib-base=3.5.1=py37ha18d171_1
  - minio=7.1.0=pyhd3eb1b0_0
  - mkl=2021.4.0=h06a4308_640
  - mkl-service=2.4.0=py37h7f8727e_0
  - mkl_fft=1.3.1=py37hd3c417c_0
  - mkl_random=1.2.2=py37h51133e4_0
  - munkres=1.1.4=py_0
  - murmurhash=1.0.7=py37h295c915_0
  - ncurses=6.3=h7f8727e_2
  - nettle=3.7.3=hbbd107a_1
  - ninja=1.7.2=0
  - numexpr=2.7.3=py37h22e1b3c_1
  - numpy=1.21.2=py37h20f2e39_0
  - numpy-base=1.21.2=py37h79a1101_0
  - olefile=0.46=py37_0
  - openh264=2.1.1=h4ff587b_0
  - openml=0.12.2=pyhd3eb1b0_0
  - openssl=1.1.1o=h7f8727e_0
  - orc=1.6.7=h973521d_2
  - packaging=21.3=pyhd3eb1b0_0
  - pandas=1.3.5=py37h8c16a72_0
  - pcre=8.45=h295c915_0
  - pillow=6.2.1=py37h34e0f95_0
  - pip=21.2.2=py37h06a4308_0
  - plac=1.1.0=py37_1
  - preshed=3.0.6=py37h295c915_0
  - protobuf=3.11.2=py37he6710b0_0
  - pyarrow=4.0.1=py37he0739d4_3
  - pycparser=2.21=pyhd3eb1b0_0
  - pyopenssl=22.0.0=pyhd3eb1b0_0
  - pyparsing=3.0.4=pyhd3eb1b0_0
  - pyqt=5.9.2=py37h05f1152_2
  - pyrsistent=0.18.0=py37heee7806_0
  - pysocks=1.7.1=py37_1
  - python=3.7.13=h12debd9_0
  - python-dateutil=2.8.2=pyhd3eb1b0_0
  - pytorch=1.7.0=py3.7_cuda10.2.89_cudnn7.6.5_0
  - pytorch-mutex=1.0=cuda
  - pytz=2021.3=pyhd3eb1b0_0
  - pyyaml=6.0=py37h7f8727e_1
  - qt=5.9.7=h5867ecd_1
  - re2=2020.11.01=h2531618_1
  - readline=8.1.2=h7f8727e_1
  - requests=2.27.1=pyhd3eb1b0_0
  - scikit-learn=1.0.2=py37h51133e4_1
  - scipy=1.7.3=py37hc147768_0
  - setuptools=58.0.4=py37h06a4308_0
  - sip=4.19.8=py37hf484d3e_0
  - six=1.16.0=pyhd3eb1b0_1
  - snappy=1.1.8=he6710b0_0
  - spacy=2.3.5=py37hff7bd54_0
  - sqlite=3.38.0=hc218d9a_0
  - srsly=1.0.5=py37h2531618_0
  - tensorboardx=2.2=pyhd3eb1b0_0
  - thinc=7.4.5=py37h9a67853_0
  - threadpoolctl=2.2.0=pyh0d69192_0
  - tk=8.6.11=h1ccaba5_0
  - torchtext=0.8.0=py37
  - torchvision=0.8.1=py37_cu102
  - tornado=6.1=py37h27cfd23_0
  - tqdm=4.64.0=py37h06a4308_0
  - typing_extensions=4.1.1=pyh06a4308_0
  - uriparser=0.9.3=he6710b0_1
  - urllib3=1.26.8=pyhd3eb1b0_0
  - utf8proc=2.6.1=h27cfd23_0
  - wasabi=0.9.1=py37h06a4308_0
  - wheel=0.37.1=pyhd3eb1b0_0
  - xmltodict=0.12.0=pyhd3eb1b0_0
  - xz=5.2.5=h7b6447c_0
  - yaml=0.2.5=h7b6447c_0
  - zipp=3.8.0=py37h06a4308_0
  - zlib=1.2.11=h7f8727e_4
  - zstd=1.4.9=haebb681_0
  - pip:
    - apex==0.1
prefix: /home/zhanxueying/miniconda3/envs/deepAL
